#!/bin/bash

set -e

CWD=$(pwd)
source $CWD/../../rocm-environment.sh

PRGNAM=rocm_bandwidth_test
cd $ROCM_REL_DIR

if [ -d $ROCM_REL_DIR/$PRGNAM ]; then
    ( cd $ROCM_REL_DIR/$PRGNAM && git clean -f -d && git reset --hard HEAD && git fetch --all --tags && git checkout ${ROCM_BRANCH} )
else
    ( cd $ROCM_REL_DIR && git clone --branch ${ROCM_BRANCH} https://github.com/ROCm/rocm_bandwidth_test.git )
fi
rm -rf $ROCM_BUILD_DIR/$PRGNAM
mkdir -p $ROCM_BUILD_DIR/$PRGNAM
cd $ROCM_BUILD_DIR/$PRGNAM

DEST=$OUTPUT/package-$PRGNAM

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
BUILD=1
rm -rf $DEST

pushd .

cmake \
    -Wno-dev \
    -G Ninja \
    -D CMAKE_CXX_COMPILER=${ROCM_INSTALL_DIR}/bin/amdclang++ \
    -D CMAKE_CXX_FLAGS="${CXXFLAGS} -fcf-protection=none -DNDEBUG" \
    -D CMAKE_C_COMPILER=${ROCM_INSTALL_DIR}/bin/amdclang \
    -D CMAKE_C_FLAGS="${CXXFLAGS} -fcf-protection=none -DNDEBUG" \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_PREFIX=$ROCM_INSTALL_DIR \
    -D CPACK_PACKAGING_INSTALL_PREFIX=$ROCM_INSTALL_DIR \
    -D CMAKE_MODULE_PATH="$ROCM_REL_DIR/$PRGNAM/cmake_modules" \
    -D CMAKE_PREFIX_PATH=$ROCM_INSTALL_DIR \
    -D AMD_APP_BUILD_DOCS=OFF \
    -D AMD_APP_BUILD_EXAMPLES=OFF \
    -D AMD_APP_DEBUG_INFO_COMPRESS=OFF \
    -D USE_LOCAL_FMT_LIB=ON \
    -D USE_LOCAL_NLOHMANN_JSON=ON \
    $ROCM_REL_DIR/$PRGNAM

"${NINJA:=ninja}" $NUMJOBS || exit 1
DESTDIR=$DEST "$NINJA" install/strip || exit 1

mkdir -p $DEST/install
cat $CWD/slack-desc > $DEST/install/slack-desc

cd $DEST
makepkg -l y -c n $OUTPUT/$PRGNAM-$PKGVER-$ARCH-${BUILD}$TAG.txz

popd
